//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelExport.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Projects\\WZ2100\\flaME\\data\\3.1_b4-objects\\pies\\")]
        public string PathPies {
            get {
                return ((string)(this["PathPies"]));
            }
            set {
                this["PathPies"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Projects\\WZ2100\\flaME\\data\\3.1_b4-objects\\texpages\\")]
        public string PathTexpages {
            get {
                return ((string)(this["PathTexpages"]));
            }
            set {
                this["PathTexpages"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Projects\\WZ2100\\WMIT 0.7.0\\WMIT.exe")]
        public string PathWMIT {
            get {
                return ((string)(this["PathWMIT"]));
            }
            set {
                this["PathWMIT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("E:\\Projects\\WZ2100\\ModelTemp\\")]
        public string PathTemp {
            get {
                return ((string)(this["PathTemp"]));
            }
            set {
                this["PathTemp"] = value;
            }
        }
    }
}
